In [1]:
#data encoding >> converting categorical columns into numeric
#Nominal/OHE
#label and ordinal encoding
#Target guided ordinal encoding

In [2]:
#Nominal/OHE >> Binary vector for each of the categories
#example single, married, separated
#single: [1, 0, 0]
#married: [0, 1, 0]
#separated: [0, 0, 1]

In [3]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
df = pd.DataFrame({"status": ["single", "married", "separated", "single", "married"]})

In [4]:
df

      status
0     single
1    married
2  separated
3     single
4    married

In [5]:
encoder = OneHotEncoder()

In [6]:
encoder

OneHotEncoder()

In [7]:
encoded = encoder.fit_transform(df[["status"]]).toarray()

In [8]:
encoded

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [9]:
encoder.get_feature_names_out()

array(['status_married', 'status_separated', 'status_single'],
      dtype=object)

In [10]:
encoder_df = pd.DataFrame(encoded, columns = encoder.get_feature_names_out())

In [11]:
encoder_df

   status_married  status_separated  status_single
0             0.0               0.0            1.0
1             1.0               0.0            0.0
2             0.0               1.0            0.0
3             0.0               0.0            1.0
4             1.0               0.0            0.0

In [12]:
encoder.transform([["single"]]).toarray()

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[0., 0., 1.]])

In [13]:
#h/w
#pd.get_dummies()

In [14]:
pd.concat([df, encoder_df], axis = 1)

      status  status_married  status_separated  status_single
0     single             0.0               0.0            1.0
1    married             1.0               0.0            0.0
2  separated             0.0               1.0            0.0
3     single             0.0               0.0            1.0
4    married             1.0               0.0            0.0

In [15]:
import seaborn as sns
sns.load_dataset("tips")

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [16]:
#label encoding >> assign unique label to the categories
# using map or using library

In [17]:
df

      status
0     single
1    married
2  separated
3     single
4    married

In [18]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

In [19]:
label_encoder.fit_transform(df[['status']])

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 2, 0])

In [20]:
label_encoder.transform([["separated"]])

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([1])

In [21]:
#ordinal encoding

#High school : 1
#gradiate: 2
#post graduate: 3
#Phd: 4

In [22]:
from sklearn.preprocessing import OrdinalEncoder
df = pd.DataFrame({"qualification": ["HS","GR", "PG", "PHD", "HS", "PHD"]})

In [23]:
df

  qualification
0            HS
1            GR
2            PG
3           PHD
4            HS
5           PHD

In [24]:
encoder = OrdinalEncoder(categories=[["HS", "GR", "PG", "PHD"]])

In [25]:
encoder.fit_transform(df[["qualification"]])

array([[0.],
       [1.],
       [2.],
       [3.],
       [0.],
       [3.]])

In [26]:
#new data
encoder.transform([["PG"]])

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[2.]])

In [27]:
#Target guided ordinal encoding
#relationship with target variable
#A lot of unique categories
#replace the category with mean and median of respective group

In [28]:
df = pd.DataFrame({'time':['lunch', 'breakfast', 'dinner', 'lunch', 'breakfast', 'dinner', 'lunch', 'breakfast', 'dinner'],
             'total_bill': [120, 130, 90, 125, 150, 190, 160, 180, 189]})

In [29]:
df

        time  total_bill
0      lunch         120
1  breakfast         130
2     dinner          90
3      lunch         125
4  breakfast         150
5     dinner         190
6      lunch         160
7  breakfast         180
8     dinner         189

In [30]:
mean_price = df.groupby('time')['total_bill'].mean().to_dict()

In [31]:
df["time_encoded"] = df['time'].map(mean_price)

In [32]:
df

        time  total_bill  time_encoded
0      lunch         120    135.000000
1  breakfast         130    153.333333
2     dinner          90    156.333333
3      lunch         125    135.000000
4  breakfast         150    153.333333
5     dinner         190    156.333333
6      lunch         160    135.000000
7  breakfast         180    153.333333
8     dinner         189    156.333333

In [33]:
sns.load_dataset("tips")

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]